#!/bin/bash

# crate directories
mkdir -p ~/.config/nvim/plugin

for f in `find . -regex ".*\.vim$\|.*.lua$"`; do
    echo "Remove ~/.config/nvim/$f"
    rm -rf ~/.config/nvim/$f
    echo "Link ~/.config/nvim/$f -> ~/.dotfiles/nvim/$f"
    ln -s ~/.dotfiles/nvim/$f ~/.config/nvim/$f
done

