# <https://github.com/rust-lang/rustfmt/blob/master/Configurations.md>

error_on_unformatted = true
use_small_heuristics = "Max"
max_width = 100
chain_width = 80
wrap_comments = false
comment_width = 80
condense_wildcard_suffixes = true
edition = "2021"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
match_block_trailing_comma = true
imports_granularity = "Crate"
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "One"
single_line_if_else_max_width = 80
single_line_let_else_max_width = 80
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
where_single_line = true
