[package]
name = "screen-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
display_macro = { version = "0.1.0", path = "~/dev/rust/display_me" }
thiserror = "1.0.37"
