# vim: set filetype=yaml.ansible :/
- name: "Go: Installing Go"
  vars:
    os: linux
    arch: amd64
    latest_version_url: "https://golang.org/VERSION?m=text"
    archive_name: "{{ latest_version }}.{{ os }}-{{ arch }}.tar.gz"
    download_url: "https://go.dev/dl/{{ archive_name }}"
    current_version: "none"
    latest_version: "{{ lookup('url', latest_version_url, split_lines=False) | split('\n') | first }}"
  block:
    - name: "Go: Try to get current go version installed"
      ansible.builtin.command: go version
      register: result
      ignore_errors: true
      changed_when: false

    - name: "Go: Set current_version variable"
      set_fact:
        current_version: "{{ result.stdout.split(' ')[2] }}"
      when: not result.failed

    - name: "Go: Download and extract the archive {{ archive_name }}"
      become: true
      ansible.builtin.unarchive:
        src: "{{ download_url }}"
        dest: /usr/local
        remote_src: true
      when: current_version != latest_version
