# vim: set filetype=yaml.ansible :/
- name: "Nvim: Installing Neovim build dependencies"
  become: true
  ansible.builtin.apt:
    name: neovim
    state: build-dep

- name: "Nvim: Cloning Neovim"
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim"
    dest: "{{ bin }}/neovim"
    update: true
    force: true
  register: git_result

- name: "Nvim: Neovim Build Process"
  when: git_result.changed
  block:
    - name: "Nvim: Removing old build directory"
      ansible.builtin.file:
        path: "{{ bin }}/neovim/build"
        state: absent

    - name: "Nvim: Building Neovim"
      ansible.builtin.command: make
      args:
        chdir: "{{ bin }}/neovim"
      environment:
        CMAKE_BUILD_TYPE: RelWithDebInfo

    - name: "Nvim: Creating and Installing Neovim .deb package"
      become: true
      ansible.builtin.command: "checkinstall --default --pakdir={{ bin }}/neovim/build"
      args:
        chdir: "{{ bin }}/neovim"
