# vim: set filetype=yaml.ansible :/
- name: "Node.js: Installing Node.js"
  become: true
  apt:
    name: nodejs

# - name: "Node.js: npmjs prefix"
#   shell: mkdir -p ~/.local/.npm-global
#   tags:
#   - install
#   - node
#
# - name: "Node.js: add npmjs to path"
#   shell: PATH=~/.local/.npm-global/bin:$PATH
#   tags:
#   - install
#   - node
#
# - name: "Node.js: npmjs global settings"
#   shell: npm config set prefix '~/.local/.npm-global'
#   tags:
#   - install
#   - node
#
# - name: "Node.js: npmjs global settings export path in case I don't have dotfiles installed"
#   shell: export PATH=~/.local/.npm-global/bin:$PATH
#   tags:
#   - install
#   - node
#   - npm-path
#
# - name: "Node.js: Install N"
#   npm:
#     name: n
#     global: yes
#   tags:
#     - install
#     - node
#
# - name: "Node.js: Install correct version of Node"
#   shell: n 14
#   tags:
#     - install
#     - node
