# vim: set filetype=yaml.ansible :/
- name: Creating extern .cargo and .rustup direcories
  become: true
  vars:
    dest: "/usr/share/rust/{{ item }}"
  ansible.builtin.file:
    dest: "{{ dest }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
    - .cargo
    - .rustup
    - .cache/sccache
  loop_control:
    label: "{{ dest }}/"

- name: Linking .cargo and .rustup
  vars:
    dest: "{{ home }}/{{ item }}"
    src: "/usr/share/rust/{{ item }}"
  ansible.builtin.file:
    dest: "{{ dest }}"
    src: "{{ src }}"
    state: link
  loop:
    - .cargo
    - .rustup
    - .cache/sccache
  loop_control:
    label: "{{ dest }} -> {{ src }}"

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ home }}/.local/share/bash-completion/completions"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Bash rustup completions
  ansible.builtin.shell:
    cmd: "rustup completions bash       > ~/.local/share/bash-completion/completions/rustup"

- name: Bash cargo completions
  ansible.builtin.shell:
    cmd: "rustup completions bash cargo > ~/.local/share/bash-completion/completions/cargo"
