# vim: set filetype=yaml.ansible :/
- name: "Rust: Bash rustup completions"
  ansible.builtin.shell:
    cmd: "rustup completions bash       > ~/.local/share/bash-completion/completions/rustup"

- name: "Rust: Bash cargo completions"
  ansible.builtin.shell:
    cmd: "rustup completions bash cargo > ~/.local/share/bash-completion/completions/cargo"

- name: "Install cargo-binstall"
  block:
    - name: "Try to get current cargo-binstall version installed"
      ansible.builtin.command: cargo binstall -V
      register: current
      ignore_errors: true
      changed_when: false

    - name: "Try to get current latest cargo-binstall version"
      ansible.builtin.shell: cargo search cargo-binstall | head -n 1 | sed 's/^cargo-binstall = "\([0-9\.]*\)"\s*#.*$/\1/'
      register: latest
      ignore_errors: true
      changed_when: false

    - name: "Set current_version and latest_version"
      set_fact:
        current_version: "{{ current.stdout | default('none', true) }}"
        latest_version: "{{ latest.stdout | default('unknown', true) }}"

    - name: "Set latest_version"
      ansible.builtin.shell: cargo search cargo-binstall | head -n 1 | sed 's/^cargo-binstall = "\([0-9\.]*\)"\s*#.*$/\1/'
      register: latest_out
      changed_when: false

    - name: "Install cargo-binstall with `cargo install`"
      community.general.cargo:
        name: cargo-binstall
      when: current_version == "none"

    - name: "Update cargo-binstall with `cargo binstall`"
      community.general.cargo:
        name: cargo-binstall
      when: current_version != "none" and current_version != latest_version

- name: "Install sccache"
  ansible.builtin.command: cargo binstall -y sccache
  environment:
    RUSTC_WRAPPER: ""

- name: "Install mprocs"
  community.general.cargo:
    name: mprocs

- name: "Install ripgrep"
  community.general.cargo:
    name: ripgrep
