# vim: set filetype=yaml.ansible :/
- name: Install sccache
  ansible.builtin.command: cargo binstall sccache
  environment:
    RUSTC_WRAPPER: ""

- name: Install mprocs
  ansible.builtin.command: cargo install mprocs

- name: Install ripgrep
  ansible.builtin.command: cargo install ripgrep
