# vim: set filetype=yaml.ansible :/
- name: Installing Starship Shell
  ansible.builtin.command: cargo install starship --locked


- name: Installing Alacritty font dependencies
  become: true
  ansible.builtin.apt:
    name:
      - libfontconfig1-dev
      - libfontconfig1

- name: Installing Alacritty Terminal
  ansible.builtin.command: cargo install alacritty
  environment:
    PKG_CONFIG_PATH: "/usr/lib/x86_64-linux-gnu/pkgconfig"

- name: Installing kitty Terminal
  ansible.builtin.shell:
    cmd: "curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin"

- name: "Link into PATH: {{ item }}"
  ansible.builtin.file:
    path: "~/.local/bin/{{ item }}"
    src: "~/.local/kitty.app/bin/{{ item }}"
    state: link
    force: true
  loop:
    - "kitty"
    - "kitten"

# - name: Installing kitty build dependencies
#   become: true
#   ansible.builtin.apt:
#     name: kitty
#     state: build-dep
#
# - name: Cloning kitty Terminal
#   ansible.builtin.git:
#     repo: "https://github.com/kovidgoyal/kitty.git"
#     dest: "{{ bin }}/kitty"
#     update: true
#     force: true
#   register: git_result
#
# - name: Building kitty Terminal
#   ansible.builtin.command:
#     cmd: ./dev.sh build
#     chdir: "{{ bin }}/kitty"
#   when: git_result.changed
