# vim: set filetype=yaml.ansible :/
- name: "Starship: Installing Starship Shell"
  community.general.cargo:
    name: starship
    locked: true

- name: "Alacritty: Installing font dependencies"
  become: true
  ansible.builtin.apt:
    name:
      - libfontconfig1-dev
      - libfontconfig1

- name: "Alacritty: Installing Alacritty Terminal"
  community.general.cargo:
    name: alacritty
  environment:
    PKG_CONFIG_PATH: "/usr/lib/x86_64-linux-gnu/pkgconfig"

- name: "Kitty: Installing kitty Terminal"
  ansible.builtin.shell:
    cmd: "curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin"

- name: "Kitty: Link into PATH: {{ item }}"
  ansible.builtin.file:
    path: "~/.local/bin/{{ item }}"
    src: "~/.local/kitty.app/bin/{{ item }}"
    state: link
    force: true
  loop:
    - "kitty"
    - "kitten"

# sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator `which kitty` 50
- name: "Kitty: Setting Kitty as default terminal"
  become: true
  community.general.alternatives:
    link: "/usr/bin/x-terminal-emulator"
    name: "x-terminal-emulator"
    path: "{{ home }}/.local/bin/kitty"
    priority: 50

# - name: "Installing kitty build dependencies"
#   become: true
#   ansible.builtin.apt:
#     name: kitty
#     state: build-dep
#
# - name: "Cloning kitty Terminal"
#   ansible.builtin.git:
#     repo: "https://github.com/kovidgoyal/kitty.git"
#     dest: "{{ bin }}/kitty"
#     update: true
#     force: true
#   register: git_result
#
# - name: "Building kitty Terminal"
#   ansible.builtin.command:
#     cmd: ./dev.sh build
#     chdir: "{{ bin }}/kitty"
#   when: git_result.changed
