local create_command = require("qwox.command")

create_command("W", "w", { desc = "Prevent misstype of :w" })
create_command("Q", "q", { desc = "Prevent misstype of :q" })
create_command("Wa", "wa", { desc = "Prevent misstype of :wa" })
create_command("WA", "wa", { desc = "Prevent misstype of :wa" })
create_command("Wq", "wq", { desc = "Prevent misstype of :wq" })
create_command("WQ", "wq", { desc = "Prevent misstype of :wq" })
create_command("Wqa", "wqa", { desc = "Prevent misstype of :wqa" })
create_command("WQa", "wqa", { desc = "Prevent misstype of :wqa" })
