#!/usr/bin/env bash

export PATH="/usr/local/bin:/usr/bin:/bin"

add_to_path() {
    path="$1"
    # affix colons on either side of $PATH to simplify matching
    case ":${PATH}:" in
        *:"$path":*)    ;; # already in path
        *)              export PATH="$path:$PATH" ;;
    esac
}

add_to_path "$HOME/bin"
add_to_path "$HOME/scripts"
add_to_path "$HOME/.local/bin"
add_to_path "$HOME/.cargo/bin"
