#!/usr/bin/env bash

# ${...-}: sets undefined to empty string
if [ -z "${PATH-}" ]; then export PATH=""; fi

PATH="/usr/local/bin:/usr/bin:/bin"

add_to_path() {
    path="$1"
    # affix colons on either side of $PATH to simplify matching
    case ":${PATH}:" in
        *:"$path":*)    ;; # already in path
        *)              PATH="$PATH:$path" ;;
    esac
}

add_to_path "$HOME/bin"
add_to_path "$HOME/.local/bin"
add_to_path "$HOME/.dotfiles/scripts"

add_to_path "$HOME/lib/llvm/llvm-project/build/bin"

add_to_path "$HOME/.cargo/bin"
add_to_path "/usr/local/go/bin"
add_to_path "$HOME/src/mylang/master/target/debug"
