#!/usr/bin/env bash

cargo doc --workspace || exit "$?"

project_path="$(cargo locate-project --workspace | sed 's_{"root":"\(.*\)/Cargo.toml"}_\1_')"

cd "$project_path/target/doc"

python3 -m http.server
